
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER3
 */
public class BusquedaVentana extends javax.swing.JFrame {

    /**
     * Creates new form BusquedaVentana
     */
    public BusquedaVentana() {
        initComponents();
        m=(DefaultTableModel) tblArticulo.getModel();
        leerArchivo();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTam = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        btnHash = new javax.swing.JButton();
        btnBusquedaSec = new javax.swing.JButton();
        btnBusquedaBinaria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnGuardarOtro = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tamaño");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        getContentPane().add(txtTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 120, -1));

        btnGenerar.setText("Generar Array ");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 150, -1));

        jLabel2.setText("Número");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));
        getContentPane().add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, -1));

        btnHash.setText("Buscar");
        btnHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHashActionPerformed(evt);
            }
        });
        getContentPane().add(btnHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 90, -1));

        btnBusquedaSec.setText("Busqueda Secuencial");
        btnBusquedaSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaSecActionPerformed(evt);
            }
        });
        getContentPane().add(btnBusquedaSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 150, -1));

        btnBusquedaBinaria.setText("Busqueda Binaria");
        btnBusquedaBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaBinariaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBusquedaBinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 150, -1));

        tblArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Clave", "Descripción ", "Precio "
            }
        ));
        jScrollPane1.setViewportView(tblArticulo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, 260));

        jLabel3.setText("Clave");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 120, -1));

        jLabel4.setText("Descrip ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));
        getContentPane().add(txtDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 120, -1));

        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 120, -1));

        btnGuardarOtro.setText("Guardar Otro");
        btnGuardarOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarOtroActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 110, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 90, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 200, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
       A=generar(Integer.parseInt(txtTam.getText())); 
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHashActionPerformed
       int pos =hash (txtClave.getText());
       if(m.getValueAt(pos,0)==null){showMessageDialog(this,"NO existe"); return;}
       while(!m.getValueAt(pos, 0).toString().equals(txtClave.getText())){
          pos++; 
          if(m.getValueAt(pos,0)==null){showMessageDialog(this,"NO existe"); return;}
       }
       
       txtDescrip.setText(m.getValueAt(pos,1).toString()); 
       txtPrecio.setText(m.getValueAt(pos,2).toString()); 
                 
    }//GEN-LAST:event_btnHashActionPerformed

    private void btnBusquedaSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaSecActionPerformed
        int pos=busquedaSec(A,Integer.parseInt(txtTam.getText()));
        if(pos==-1)showMessageDialog(this, "No se encuentra"); 
        else showMessageDialog(this, "Se encuentra en la posición="+pos); 
    }//GEN-LAST:event_btnBusquedaSecActionPerformed

    private void btnBusquedaBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaBinariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusquedaBinariaActionPerformed
    
    public int hash(String c){
        int s=0;
        for(int i=0; i<c.length(); i++) s+=c.charAt(i);
        return s%100; 
    }
    
    private void btnGuardarOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarOtroActionPerformed
       int pos =hash (txtClave.getText());
       if(!m.getValueAt(pos, 0).toString().equals("") && !m.getValueAt(pos, 1).toString().equals(txtClave.getText()))pos++; 
       while(!m.getValueAt(pos, 0).toString().equals(""))pos++; 
       m.setValueAt(txtClave.getText(), pos, 0); 
       m.setValueAt(txtDescrip.getText(), pos, 1);
       m.setValueAt(txtPrecio.getText(), pos, 2);
       txtClave.setText(""); 
       txtDescrip.setText(""); 
       txtPrecio.setText(""); 
       
    }//GEN-LAST:event_btnGuardarOtroActionPerformed
    public void guardarArchivo(){
          try { 
            fs=new java.io.FileWriter("Articulo.txt");
              for (int i = 0; i < m.getRowCount(); i++) {
                  if(m.getValueAt(i, 0)!=null)
                  a=new Articulo(m.getValueAt(i, 0).toString(),m.getValueAt(i, 1).toString(),Float.parseFloat(m.getValueAt(i, 2).toString()));
                  else a=new Articulo ("","",0);
                  a.guardar(fs);
                  
              }
        } catch (IOException ex) {
             showMessageDialog(this, ex.getMessage());
        }
        
    }
    
    public void leerArchivo(){
        try {
            fe = new java.io.FileReader("Articulo.txt");
            br=new java.io.BufferedReader(fe);
            String reg="";
            
            for (int i = 0; i < 100; i++) {
                reg=br.readLine();
                String R[] = reg.split("\\|");
                m.setValueAt(R[0], i, 0);
                m.setValueAt(R[1], i, 1);
                m.setValueAt(R[2], i, 2);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BusquedaVentana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BusquedaVentana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        guardarArchivo();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int pos =hash (txtClave.getText());
       while(!m.getValueAt(pos, 0).toString().equals(""))pos++; 
       m.setValueAt(txtClave.getText(), pos, 0); 
       m.setValueAt(txtDescrip.getText(), pos, 1);
       m.setValueAt(txtPrecio.getText(), pos, 2);
       txtClave.setText(""); 
       txtDescrip.setText(""); 
       txtPrecio.setText(""); 
        
    }//GEN-LAST:event_btnGuardarActionPerformed
    private DefaultTableModel m; 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaVentana().setVisible(true);
            }
        });
    }
    //TAREA BUSQUEDA BINARIA 
    
    public int busquedaSec(int A[],int c){
        for (int i = 0; i < A.length; i++){ 
            if(A[i]==c)return i;}
            return -1; 
            
        
    }//Busqueda Secuencial 
    public int[] generar(int n){
        int A[]= new int[n]; 
        for (int i = 0; i <n; i++) 
        {A[i]=(int)(Math.random()*1000);System.out.println(A[i]);}
            return A; 
            
        
    }// Llenar arreglo 
       private int A[],n=0;
       private java.io.FileWriter fs; 
       private java.io.FileReader fe; 
       private java.io.BufferedReader br; 
       private Articulo a; 
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaBinaria;
    private javax.swing.JButton btnBusquedaSec;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarOtro;
    private javax.swing.JButton btnHash;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArticulo;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
