
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.EventQueue;
import javafx.scene.input.KeyCode;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.MatteBorder;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ColaVentana extends javax.swing.JFrame {

    /**
     * Creates new form ColaVentana
     */
    public ColaVentana() {
        initComponents();
        
        txtDat.requestFocus();
        m = (DefaultTableModel) tblT.getModel();
        
        //Color c = new Color(255,255,255,0);
        tblT.setBackground(Color.white);
        tblT.setShowGrid(true);
        MatteBorder border = new MatteBorder(1, 1, 0, 0, Color.black);
        tblT.setBorder(border);
        
        
        
        
        col = new ColaCircular(m.getColumnCount());
        //tblT.setTableHeader(null);
        tblT.getTableHeader().setVisible(false);
        
        tblT.setValueAt("Inicio", 0, 0);
        lblInicio.setText("0");
        lblFin.setText("0");
        tblT.setValueAt("Fin", 2, 0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblT = new javax.swing.JTable();
        btnPush = new javax.swing.JButton();
        btnPop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDat = new javax.swing.JTextField();
        btnEmpt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTam = new javax.swing.JTextField();
        btnCamb = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFin = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tblT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Inicio", null, null, null, null},
                {null, null, null, null, null},
                {"Fin", null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        tblT.setRowHeight(30);
        tblT.setRowSelectionAllowed(false);
        tblT.setShowHorizontalLines(false);
        tblT.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblT);

        btnPush.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IMAGENES COLA/login.png"))); // NOI18N
        btnPush.setText("PUSH");
        btnPush.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPushMouseClicked(evt);
            }
        });

        btnPop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IMAGENES COLA/basura.png"))); // NOI18N
        btnPop.setText("POP");
        btnPop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPopMouseClicked(evt);
            }
        });

        jLabel1.setText("Tamaño:");

        jLabel2.setText("Ingresa un dato: ");

        txtDat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatKeyTyped(evt);
            }
        });

        btnEmpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IMAGENES COLA/empty-cart.png"))); // NOI18N
        btnEmpt.setText("VACIAR");
        btnEmpt.setToolTipText("");
        btnEmpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("COLAS CIRCULARES");

        txtTam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamKeyTyped(evt);
            }
        });

        btnCamb.setText("Cambiar");
        btnCamb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambMouseClicked(evt);
            }
        });

        jLabel5.setText("Inicio:");

        jLabel6.setText("Fin:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPush, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnCamb))
                                    .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDat)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPop, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnEmpt)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCamb)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPush)
                            .addComponent(btnPop)
                            .addComponent(btnEmpt)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(lblFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtTamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtTamKeyTyped

    private void txtTamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTamKeyReleased
    
    private void validaTam(JTextField txt)throws ColaException{
        if(txtTam.getText().length()==0)throw new ColaException("Campo vacío");
        String c = txt.getText();
        for (int i = 0; i < c.length(); i++) {
            if(c.charAt(i)<48 || c.charAt(i)>57) throw new ColaException("Solo números");
        } 
    }
    
    private void validaDato(JTextField txt)throws ColaException{
        if(txt.getText().length()==0){txtDat.requestFocus(); throw new ColaException("Campo vacío");}
    }
    
    private boolean validado(JTextField t){
        try{
          validaTam(t);  
        }catch(ColaException err){
            showMessageDialog(this, err.getMessage());
            txtTam.setText("");
            return false;
        }
        
        return true;
    }
    private boolean dValidado(JTextField t){
        try{
          validaDato(t);  
        }catch(ColaException err){
            showMessageDialog(this, err.getMessage());
            return false;
        }
        
        return true;
    }
    
    private void btnCambMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambMouseClicked
        if(!validado(txtTam))return;
        int t = Integer.parseInt(txtTam.getText());
        try{
            m.setColumnCount(t);
            col = new ColaCircular(Integer.parseInt(txtTam.getText()));
            
        }catch(ColaException err){
            showMessageDialog(this, err.getMessage());
        }
        
    }//GEN-LAST:event_btnCambMouseClicked

    public void push(){
        
        btnCamb.setEnabled(false);
        if(!dValidado(txtDat))return;
        if(col.getInicio()==-1 && !col.llena())tblT.setValueAt("", 2, 0);
        else if(!col.llena())tblT.setValueAt("", 2, col.getFin());
        if(col.getFin()==(m.getColumnCount()-1)){
            try{
                col.push(txtDat.getText());
                tblT.setValueAt("Fin", 2, 0);
                tblT.setValueAt(txtDat.getText(), 1, 0);
                lblFin.setText(""+col.getFin());
                if (col.getFin() == 0 && col.getInicio() == -1) {
                    col.setFin(-1);
                }
                if (col.getInicio() == -1) {
                col.setInicio(0);
                m.setValueAt("Inicio", 0, 0);
                }
                tblT.repaint();
                txtDat.setText("");
                txtDat.requestFocus();
            }catch(ColaException ex){
                showMessageDialog(this, ex.getMessage());
            }
        }
        
        else{
            try{
                col.push(txtDat.getText());
                if(col.getFin()==m.getColumnCount()) tblT.setValueAt(txtDat.getText(), 1, 0);
                tblT.setValueAt(txtDat.getText(), 1, col.getFin());
                if(col.getFin()==m.getColumnCount()) tblT.setValueAt("Fin", 2, 0);
                tblT.setValueAt("Fin", 2, col.getFin());
                lblFin.setText(""+col.getFin());
                tblT.repaint();
                txtDat.setText("");
                txtDat.requestFocus();
            }catch(ColaException err){
                showMessageDialog(this, err.getMessage());
            }
        }
        
    }
    
    private void btnPushMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPushMouseClicked
        push();        
    }//GEN-LAST:event_btnPushMouseClicked

    private void btnPopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPopMouseClicked
        if(col.vacia()){showMessageDialog(this, "Cola vacía"); eliminar();}
        if(col.getInicio()==col.getFin()){
            try{
                showMessageDialog(this, "Cola vacía");
                tblT.setValueAt("", 1, col.getInicio());
                //col.pop2();
                //lblInicio.setText(""+col.getInicio());
                eliminar();
                tblT.repaint();
            }catch(ColaException ex){
                showMessageDialog(this, ex.getMessage());
            }
        }
        else{
            try{
                tblT.setValueAt("", 0, col.getInicio());
                tblT.setValueAt("", 1, col.getInicio());
                col.pop2();
                tblT.setValueAt("Inicio", 0, col.getInicio());
                lblInicio.setText(""+col.getInicio());
                tblT.repaint();
            }catch(ColaException err){
                showMessageDialog(this, err.getMessage());
            }
        }
    }//GEN-LAST:event_btnPopMouseClicked

    private void eliminar(){
        for (int i = 0; i < m.getColumnCount(); i++) {
         if(!col.vacia())col.pop2();
         m.setValueAt("", 0, i);
         m.setValueAt("", 1, i);
         m.setValueAt("", 2, i);
        }
        
        m.setValueAt("Inicio", 0, 0);
        m.setValueAt("Fin", 2, 0);
        btnCamb.setEnabled(true);
        lblInicio.setText("0");
        lblFin.setText("0");
        
    }
    
    private void btnEmptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptActionPerformed
        ImageIcon icon = new ImageIcon("src/Imagenes/IMAGENES COLA/empty-cart.png");
        int res = JOptionPane.showConfirmDialog(this, "Los datos se eliminarán, ¿desea continuar?", "Vaciar tabla", YES_NO_OPTION, INFORMATION_MESSAGE, icon);
        if(res==0)eliminar();
        
    }//GEN-LAST:event_btnEmptActionPerformed

    private void txtDatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatKeyTyped
        
    }//GEN-LAST:event_txtDatKeyTyped

    private void txtDatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            push();
        }
    }//GEN-LAST:event_txtDatKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColaVentana().setVisible(true);
            }
        });
    }
    
    public DefaultTableModel m;
    ColaCircular col;
    //int tam = -1, inicio = -1, fin = -1;
    //public String C[];

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamb;
    private javax.swing.JButton btnEmpt;
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnPush;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFin;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JTable tblT;
    private javax.swing.JTextField txtDat;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables

    
}
