
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ColaDobleVentana extends javax.swing.JFrame {

    /**
     * Creates new form ColaDobleVentana
     */
    public ColaDobleVentana() {
        initComponents();
        this.setSize(691, 364);
        this.setLocationRelativeTo(null);
        
        txtDat.requestFocus();
        m = (DefaultTableModel) tblT.getModel();
        
        Color c = new Color(225,239,248);
        
        btnEntradaIzquierda.setBackground(c);
        btnEntradaDerecha.setBackground(c);
        btnSalidaIzq.setBackground(c);
        btnSalidaDerecha.setBackground(c);
        btnCamb.setBackground(c);
        btnEmpt.setBackground(c);
        tblT.setBackground(c);
        
        tblT.setBackground(Color.white);
        tblT.setShowGrid(true);
        MatteBorder border = new MatteBorder(1, 1, 0, 0, Color.black);
        tblT.setBorder(border);
        
        col = new ColaDoble(m.getColumnCount());
        tblT.getTableHeader().setVisible(false);
        
        setColmRend();
        
        
        tblT.setValueAt("|||", 0 ,col.getTam()/2 );
        col.setIzq(col.getTam()/2);
        col.setDerc(col.getTam()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblT = new javax.swing.JTable();
        btnEntradaDerecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDat = new javax.swing.JTextField();
        btnEmpt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTam = new javax.swing.JTextField();
        btnCamb = new javax.swing.JButton();
        btnEntradaIzquierda = new javax.swing.JButton();
        btnSalidaIzq = new javax.swing.JButton();
        btnSalidaDerecha = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(691, 364));

        tblT.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tblT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        tblT.setRowHeight(45);
        tblT.setRowSelectionAllowed(false);
        tblT.setShowHorizontalLines(false);
        tblT.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblT);

        btnEntradaDerecha.setBackground(new java.awt.Color(225, 239, 248));
        btnEntradaDerecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEntradaDerecha.setForeground(new java.awt.Color(0, 102, 153));
        btnEntradaDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMG/pointL.png"))); // NOI18N
        btnEntradaDerecha.setText("ED");
        btnEntradaDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradaDerechaMouseClicked(evt);
            }
        });
        btnEntradaDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaDerechaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/simbolo-de-interfaz-de-tamano-de-forma.png"))); // NOI18N
        jLabel1.setText("Tamaño:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/boton-de-inicio-de-sesion.png"))); // NOI18N
        jLabel2.setText("Dato:");

        txtDat.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatKeyTyped(evt);
            }
        });

        btnEmpt.setBackground(new java.awt.Color(225, 239, 248));
        btnEmpt.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnEmpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/empty-cart.png"))); // NOI18N
        btnEmpt.setText("VACIAR");
        btnEmpt.setToolTipText("");
        btnEmpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("COLA DOBLE");

        txtTam.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamActionPerformed(evt);
            }
        });
        txtTam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamKeyTyped(evt);
            }
        });

        btnCamb.setBackground(new java.awt.Color(225, 239, 248));
        btnCamb.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnCamb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/recargar.png"))); // NOI18N
        btnCamb.setText("CAMBIAR");
        btnCamb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambMouseClicked(evt);
            }
        });
        btnCamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambActionPerformed(evt);
            }
        });

        btnEntradaIzquierda.setBackground(new java.awt.Color(225, 239, 248));
        btnEntradaIzquierda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEntradaIzquierda.setForeground(new java.awt.Color(0, 102, 153));
        btnEntradaIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMG/pointR.png"))); // NOI18N
        btnEntradaIzquierda.setText("EI");
        btnEntradaIzquierda.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEntradaIzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradaIzquierdaMouseClicked(evt);
            }
        });

        btnSalidaIzq.setBackground(new java.awt.Color(225, 239, 248));
        btnSalidaIzq.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalidaIzq.setForeground(new java.awt.Color(0, 102, 153));
        btnSalidaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMG/pointL.png"))); // NOI18N
        btnSalidaIzq.setText("SI");
        btnSalidaIzq.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSalidaIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalidaIzqMouseClicked(evt);
            }
        });
        btnSalidaIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaIzqActionPerformed(evt);
            }
        });

        btnSalidaDerecha.setBackground(new java.awt.Color(225, 239, 248));
        btnSalidaDerecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalidaDerecha.setForeground(new java.awt.Color(0, 102, 153));
        btnSalidaDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMG/pointR.png"))); // NOI18N
        btnSalidaDerecha.setText("SD");
        btnSalidaDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalidaDerechaMouseClicked(evt);
            }
        });

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IMG/Background.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnEntradaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnSalidaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(btnCamb, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(btnSalidaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(txtDat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(btnEntradaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnEmpt, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addComponent(btnEntradaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnSalidaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnCamb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(btnSalidaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(txtDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(btnEntradaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(btnEmpt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void validaTam(JTextField txt)throws ColaException{
        if(txtTam.getText().length()==0)throw new ColaException("Campo vacío");
        String c = txt.getText();
        for (int i = 0; i < c.length(); i++) {
            if(c.charAt(i)<48 || c.charAt(i)>57) throw new ColaException("Solo números");
        } 
    }
     private void validaDato(JTextField txt)throws ColaException{
        if(txt.getText().length()==0){txtDat.requestFocus(); throw new ColaException("Campo vacío");}
    }
    
    private boolean validado(JTextField t){
        try{
          validaTam(t);  
        }catch(ColaException err){
            showMessageDialog(this, err.getMessage());
            txtTam.setText("");
            return false;
        }
        
        return true;
    }
    private boolean dValidado(JTextField t){
        try{
          validaDato(t);  
        }catch(ColaException err){
            showMessageDialog(this, err.getMessage());
            return false;
        }
        
        return true;
    }
    
    private void btnEntradaDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradaDerechaMouseClicked
        pushDer();
    }//GEN-LAST:event_btnEntradaDerechaMouseClicked
    
    
    private void txtDatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtDat.getText().length()==0){
                showMessageDialog(this, "Campo vacío");
                txtDat.transferFocus();return;
            }else if(col.llena()){
                showMessageDialog(this, "La cola está llena");
                txtDat.transferFocus();return;
            }else pushDer();
        }
    }//GEN-LAST:event_txtDatKeyReleased

    private void txtDatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatKeyTyped

    }//GEN-LAST:event_txtDatKeyTyped

    private void btnEmptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptActionPerformed
        ImageIcon icon = new ImageIcon("src/Imagenes/IMAGENES COLA/empty-cart.png");
        int res = JOptionPane.showConfirmDialog(this, "Los datos se eliminarán, ¿desea continuar?", "Vaciar tabla", YES_NO_OPTION, INFORMATION_MESSAGE, icon);
        if(res==0)eliminar();
    }//GEN-LAST:event_btnEmptActionPerformed

    private void txtTamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamKeyReleased
      

    }//GEN-LAST:event_txtTamKeyReleased

    private void txtTamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTamKeyTyped

    private void btnCambMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambMouseClicked
        
    }//GEN-LAST:event_btnCambMouseClicked
     
    public void pushDer(){
        btnCamb.setEnabled(false);
        if(!dValidado(txtDat))return;
        else if(col.llena())showMessageDialog(null,"Llena");
        else if(col.getDerc()==col.getTam()-1){showMessageDialog(this,"Llena por derecha"); txtDat.requestFocus(); return;}
        else{
            try{
                if(col.getDerc()==-1){col.setDerc(col.getTam()/2);}
                col.entradaDer(txtDat.getText());
                tblT.setValueAt(txtDat.getText(), 0,col.getDerc() );
                tblT.repaint();
                txtDat.setText("");
                txtDat.requestFocus();
            }catch(ColaException err){
                showMessageDialog(this, err.getMessage());
            }
        }
        
    }
    public void pushIzq(){
       btnCamb.setEnabled(false);
        if(!dValidado(txtDat))return;
        else if(col.llena())showMessageDialog(null,"Llena"); 
        else if(col.getIzq()==0){showMessageDialog(this,"Llena por izquierda"); txtDat.requestFocus(); return;}
        else{
            try{
                if(col.getIzq()==-1){col.setIzq(col.getTam()/2);}
                col.entradaIzq(txtDat.getText());
                tblT.setValueAt(txtDat.getText(), 0,col.getIzq() );
                tblT.repaint();
                txtDat.setText("");
                txtDat.requestFocus();
            }catch(ColaException err){
                showMessageDialog(this, err.getMessage());
            }
        }
        
    }
    public void popDer(){
        btnCamb.setEnabled(false);
        if(col.getDerc()==0){showMessageDialog(null,"Vacia");eliminar();}     
        else{  
            try{
                tblT.setValueAt("", 0,col.getDerc() );
                col.salidaDer();
                tblT.repaint();
                txtDat.setText("");
                txtDat.requestFocus();
            }catch(ColaException err){
                showMessageDialog(this, err.getMessage());
            }     
         }
    }
    public void popIzq(){
        btnCamb.setEnabled(false);
        if(col.getIzq()==col.getTam()-1){showMessageDialog(null,"Vacia"); eliminar();}       
        else{
            try{
                tblT.setValueAt("", 0,col.getIzq() );
                col.salidaIzq();
                tblT.repaint();
                txtDat.setText("");
                txtDat.requestFocus();
            }catch(ColaException err){
                        showMessageDialog(this, err.getMessage());
            }
        }
        
    }
    
    private void btnCambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambActionPerformed
        if(!validado(txtTam))return;
        int t = Integer.parseInt(txtTam.getText());
        try{
            col = new ColaDoble(Integer.parseInt(txtTam.getText()));
            m.setColumnCount(t);
            setColmRend();
            eliminar();
        }catch(ColaException err){
            showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_btnCambActionPerformed

    private void btnEntradaIzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradaIzquierdaMouseClicked
        pushIzq();
    }//GEN-LAST:event_btnEntradaIzquierdaMouseClicked

    private void btnSalidaIzqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaIzqMouseClicked
        popIzq();
    }//GEN-LAST:event_btnSalidaIzqMouseClicked

    private void btnSalidaIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaIzqActionPerformed

    private void btnEntradaDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaDerechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradaDerechaActionPerformed

    private void txtTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamActionPerformed

    private void btnSalidaDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaDerechaMouseClicked
        popDer();
    }//GEN-LAST:event_btnSalidaDerechaMouseClicked

    private void setColmRend(){
        centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );
        for (int i = 0; i < col.getTam(); i++) {
            tblT.getColumnModel().getColumn(i).setCellRenderer( centerRenderer );
        }
    }
    
    private void eliminar(){
        for (int i = 0; i < col.getTam(); i++) {
            tblT.setValueAt("", 0, i);
        }
        
        setColmRend();
        
        col.setDerc(col.getTam()/2);
        col.setIzq(col.getTam()/2);
        tblT.setValueAt("|||", 0, col.getTam()/2);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColaDobleVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColaDobleVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColaDobleVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColaDobleVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColaDobleVentana().setVisible(true);
            }
        });
    }
    public DefaultTableModel m;
    ColaDoble col;
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamb;
    private javax.swing.JButton btnEmpt;
    private javax.swing.JButton btnEntradaDerecha;
    private javax.swing.JButton btnEntradaIzquierda;
    private javax.swing.JButton btnSalidaDerecha;
    private javax.swing.JButton btnSalidaIzq;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblT;
    private javax.swing.JTextField txtDat;
    private javax.swing.JTextField txtTam;
    // End of variables declaration//GEN-END:variables
}
